# 🚀 Render.com Configuration for WebCore v2

databases:
  - name: webcore-db
    databaseName: webcore
    user: webcore
    region: oregon # أو singapore للشرق الأوسط

services:
  # 🔧 Backend API Service
  - type: web
    name: webcore-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter # $7/month
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: webcore-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        value: https://webcore-frontend.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: UPLOAD_MAX_SIZE
        value: 10485760
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000
      - key: COMPRESSION_ENABLED
        value: true

  # 🎨 Frontend Static Site
  - type: web
    name: webcore-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: VITE_API_BASE_URL
        value: https://webcore-backend.onrender.com
      - key: VITE_APP_NAME
        value: WebCore Dashboard
      - key: VITE_APP_VERSION
        value: 2.0.0
